@startsalt ui_shorten
    title Shorten URL page

    {^"Shorten URL"
      Username       | "Username"
      URL            | "https://www.google.com/search?q=TPXImpact"
      Customisation  | "xxxxx"
      [ Reset ]     | [ Shorten ]
    }
@endsalt

@startsalt ui_shorten_result
    title Shorten URL result page

    {^"Result"
      Username       | Username
      URL            | https://www.google.com/search?q=TPXImpact

      Shortened URL  | http://xxxxx/
      [ Shorten Another ]
    }
@endsalt



